# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Li Tang's Site
email: litang.cv@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Li Tang's site.
aboutme: >-
  I am a PhD candidate at ZJU Robotics Lab (ZJURL), Zhejiang University since 2015.
  My research interest is focused on visual localization. Besides, I am interested in everything in robotics.
  <br/><br/>
  I am now a visitor in Autonomous Systems Lab (ASL), ETH Zurich (since Sept. 2019), and I visited UTS Centre for Autonomous Systems (CAS) from Oct. 2017 to Jan. 2018.
baseurl: ""
url: "tangli.site"
twitter_username: ""
github_username:  dawnos

# Build settings
remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode

include:
  - "_pages"

collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # Academic projects
  - scope:
      path: "_projects/academic"
      type: projects
    values:
      tags: academic
      previous: nil
      next: nil
      # sidebar:
        # nav: "academic"
      # author_profile: true
      # author: Li Tang


search: true

main_page: "/academic/"
